### ISSUE TITLE
template repo

### ISSUE THREAD

**Issue by evanwill** [CollectionBuilder/collectionbuilder-gh#15]
new github feature,
https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository

@dcnb @owikle might be the best way for folks to start their own CB-gh?  

It is just like import, except it throws out all the commit history, so you have a new repository with just one initial commit.
pluses:
- one button click (once enabled, it adds a green button)
- smaller repository since dev history isn't there
- adds "generated from " below repo title (like "forked from "). 

example, https://github.com/evanwill/test-template

**Comment by dcnb** [comment]
That is a great feature. We should definitely use that.

Any reason why not to use it for both the skin and gh versions?

**Comment by evanwill** [comment]
Not sure, the current skin method (create repo, download release) ensures they use a release (that matches current documentation) and seems sort of clean. Using CB-skin as a template saves some clicks, seems intuitive, but we need to make sure the master is the "release" version at all times (do dev from a different branch and merge back only when releasing).
