### ISSUE TITLE
Template not working because files bigger than 10mb

### ISSUE THREAD

**Issue by dcnb** [CollectionBuilder/collectionbuilder-gh#17]
Did we not test this before today?

![image](https://user-images.githubusercontent.com/10931737/73010284-029f4500-3dc7-11ea-8de4-c0326bfd82e2.png)

**Comment by evanwill** [comment]
dude, didn't realize you dumped 25MB of Fugue and 58MB of Gem in this poor repository...

**Comment by evanwill** [comment]
@dcnb @owikle works now, https://github.com/evanwill/test-gh-now
none of the big files were even being used by the metadata
