### ISSUE TITLE
pretty vs ugly urls

### ISSUE THREAD

**Issue by evanwill** [CollectionBuilder/collectionbuilder-gh#23]
@owikle @dcnb -GH uses pretty urls (`/about/`, following usual Jekyll conventions), -CDM uses non-pretty urls (`/about.html`, following Devin's conventions). 
I haven't found anything that mentions any real advantages either way, other than just readability and saving people typing ".html" if they are manually writing out a link... 
I sort of like the pretty urls, but don't feel strongly about it, and it does make the output folder look more complicated (only to the person copying it to the server)--
anyway: seems like we should converge on one style.

**Comment by dcnb** [comment]
I vote ugly— mainly in that when I was showing it to Zach and showing him
the site folder that he would copy from, it looked way more complicated
than it is, due to all the extra folders.

**Comment by evanwill** [comment]
ugly now

5c57805911c8939b2de5f588e1c05888a044e111

**Comment by dcnb** [comment]
UGLY FOREVER!
