### ISSUE TITLE
should -GH have a youtubeid column?

### ISSUE THREAD

**Issue by evanwill** [CollectionBuilder/collectionbuilder-gh#27]
Currently CB-GH logic for youtube display is based on "format" = video, and youtubeid is added as the "filename".

CB-CDM the logic is based on youtubeid instead, if it is present or not. This makes sense, since there is a cdmid column, so each is basically designating a different API to use. 

Would having a separate youtubeid column make things more clear in CB-GH? (less confusing to have filename sometimes be an actual file, and sometimes an id) or more confusing?
Having a youtubeid would make transferring things between the two easier.
@dcnb @owikle

**Comment by dcnb** [comment]
I think youtubeid. 

I found it kind of confusing when I was just editing the files for mukurtu. And would separate out the logic a bit more if anyone wanted to mess with it later. 

Also, what if there's a case where you want a youtubeid and a filename ... 💥

**Comment by evanwill** [comment]
okay-- soon to be done

**Comment by evanwill** [comment]
done 97d86e59164c297bd1a96efcd67445a5833c8f81
