### ISSUE TITLE
Map breaks if item missing a format

### ISSUE THREAD

**Issue by dcnb** [CollectionBuilder/collectionbuilder-gh#49]
We should account for this

**Comment by evanwill** [comment]
it is accounted for by being *required* field :wink: 

yeah, I started fixing all the "null" value issues in js in cb-csv (its from doing this sort of check `if (feature.properties.format.includes("audio"))`), and cleaning up the fall backs. I didn't do map-js yet, but will polish it up there, then migrate here.

**Comment by evanwill** [comment]
fixed
