### ISSUE TITLE
How to localize the interface into another language

### ISSUE THREAD

**Issue by arojascastro** [CollectionBuilder/collectionbuilder-gh#53]
Hello, 

I am loving your Collection Builder -- thanks a lot for creating this great software!

I am still testing it but I was wondering how could I localize the interface into Spanish -- things like the navigation tabs and the metadata tags, etc. 

@jenniferisasi is also interested. We could team up somehow.

Thanks!

**Comment by evanwill** [comment]
@arojascastro thanks for the question--we haven't built that ability in configuration, but it is not *very* difficult to edit the template. Most UI element labels are driven by choices in the config files or your metadata, so there are just a few places where you need to update the text labels of some buttons.
I think @owikle has a list of the exact places to update, so I will let her chime in. Eventually we will create a doc page with that information. (Or potentially create a means to configure the labels centrally?)

Here is a recent demo example in Turkish, https://digitalottomans.github.io/demo/

**Comment by arojascastro** [comment]
Thank you! @jenniferisasi and I will look in soon -- any documentation or list with places would be a great help.

**Comment by owikle** [comment]
@arojascastro thanks for getting in touch! I recently sent some instructions to a user who wanted to change all of the buttons and default text to another language, and now I've just moved that content into our documentation so you can follow it there: https://collectionbuilder.github.io/cb-docs/docs/advanced/language/. It should get you started but it's still rough so if you have questions just let me know!

And as Evan mentioned, you can change text in the nav and in the metadata fields on the item pages using the config-csvs (https://collectionbuilder.github.io/cb-docs/docs/customization/).

**Comment by arojascastro** [comment]
Amazing! We will work a little on it and get back in case of doubt. You can close here if you want. Many thanks!
