### ISSUE TITLE
add a license

### ISSUE THREAD

**Issue by evanwill** [CollectionBuilder/collectionbuilder-gh#6]
@dcnb @owikle @jylisadoney we need to decide a license for CollectionBuilder stuff, see [choose a license](https://choosealicense.com/). 

Gil and Marii's Wax, Jekyll, Liquid, Bootstrap, and a lot of Jekyll themes are licensed [MIT](https://choosealicense.com/licenses/mit/), which is probably the simplest.

Some use [GPL3](https://choosealicense.com/licenses/gpl-3.0/) which is a bit more like cc-by-sa, but can cause problems for people reusing things. It is used by WordPress and technically required for all WP themes and plugins, and by a lot of Linux programs.

**Comment by evanwill** [comment]
Okay, @dcnb says MIT, any final thoughts @owikle or @jylisadoney ?

**Comment by owikle** [comment]
@evanwill after looking through them I think MIT is the easiest to go with.

**Comment by evanwill** [comment]
done here 7ae0340936b7611288e0077b01b15d187a95e5fc
