### ISSUE TITLE
Other ESRI maps?

### ISSUE THREAD

**Issue by writingafterthedisaster** [CollectionBuilder/collectionbuilder-gh#61]
Currently, three basemaps are available for use: Esri_WorldStreetMap, Esri_NatGeoWorldMap, Esri_WorldImagery. Is it possible to add other basemaps?

**Comment by evanwill** [comment]
@writingafterthedisaster thanks for the question--> I am going to answer this over in our main [Discussions board](https://github.com/CollectionBuilder/collectionbuilder.github.io/discussions/53) since I think other people might be interested as well.
