### ISSUE TITLE
missing demo item videos

### ISSUE THREAD

**Issue by evanwill** [CollectionBuilder/collectionbuilder-gh#79]
Keeping Watch videos used in demo metadata on CDIL server are giving 404s-- @dcnb looks like maybe location of items was rearranged on the server? 
e.g. 
item: https://collectionbuilder.github.io/collectionbuilder-gh/item.html?id=demo_008#demo_010
broken link: https://cdil.lib.uidaho.edu/keeping-watch/objects/hell-s-half-acre/patrick_records_weather.MP4

I think the link changed to: https://cdil.lib.uidaho.edu/keeping-watch/objects/videos/patrick_records_weather.MP4

but just wanted to check in to make sure (and that this is the stable location) before swapping links out. 
This probably impacts all the demo-compoundobjects-metadata examples

**Comment by dcnb** [comment]
Shoot! I changed that last week with Michael but forgot about the demo piece. I put copies of the videos back in their regular places so no 404s on demo sites for now. I'll go in and change the links too ...

**Comment by evanwill** [comment]
thanks!
